//PRODUCT
export const PRODUCT_LIST_REQ = 'PRODUCT_LIST_REQ';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';
export const PRODUCT_DETAILS_REQ = 'PRODUCT_DETAILS_REQ';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_DELETE_REQ = 'PRODUCT_DELETE_REQ';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';

export const PRODUCT_CREATE_REQ = 'PRODUCT_CREATE_REQ';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL';
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET';

//CART
export const CART_ADD_ITEM = 'CART_ADD_ITEM ';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM ';
export const SAVE_SHIPPING_ADD = 'SAVE_SHIPPING_ADD';
export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD';

//ORDER
export const ORDER_CREATE_REQ = 'ORDER_CREATE_REQ';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_DETAILS_REQ = 'ORDER_DETAILS_REQ';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';
export const ORDER_PAY_REQ = 'ORDER_PAY_REQ';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_RESET = 'RESET';

export const ORDER_USERLIST_REQ = 'ORDER_USERLIST_REQ';
export const ORDER_USERLIST_SUCCESS = 'ORDER_USERLIST_SUCCESS';
export const ORDER_USERLIST_FAIL = 'ORDER_USERLIST_FAIL';
export const ORDER_USERLIST_RESET = 'ORDER_USERLIST_RESET';

//LOGIN
export const USER_LOGIN_REQ = 'USER_LOGIN_REQ';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_RESET = 'USER_RESET';

//REGISTER
export const USER_REGISTER_REQ = 'USER_REGISTER_REQ';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

//USER DETAILS
export const USER_DETAILS_REQ = 'USER_DETAILS_REQ';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

//UPDATE USER DETAILS (PROFILE BY USER)
export const USER_UPDATE_DETAILS_REQ = 'USER_UPDATE_DETAILS_REQ';
export const USER_UPDATE_DETAILS_SUCCESS = 'USER_UPDATE_DETAILS_SUCCESS';
export const USER_UPDATE_DETAILS_FAIL = 'USER_UPDATE_DETAILS_FAIL';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

//UPDATE USER DETAILS (BY ADMIN)
export const USER_UPDATE_ADMIN_REQ = 'USER_UPDATE_ADMIN_REQ';
export const USER_UPDATE_ADMIN_SUCCESS = 'USER_UPDATE_ADMIN_SUCCESS';
export const USER_UPDATE_ADMIN_FAIL = 'USER_UPDATE_ADMIN_FAIL';
export const USER_UPDATE_ADMIN_RESET = 'USER_UPDATE_ADMIN_RESET';

//USER LIST
export const USER_LIST_REQ = 'USER_LIST_REQ';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

//USER DELETE
export const USER_DELETE_REQ = 'USER_DELETE_REQ';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';
